export default {
  ignores: [
    "dist/*",
    "package-lock.json",
    "**/tsconfig*.json",
    "src/**/*.js",
    // Generated by scripts/gas/bundle.mjs from dist/.
    "scripts/gas/Library.js",
    // Written by release-please from the commit messages, and never by hand:
    // a `[ ]` inside a description reads as a broken link reference here, and
    // there is nothing to fix at this end.
    "CHANGELOG.md",
    // Vendored agent skills, kept byte-for-byte as their source publishes them.
    ".agents/**",
    ".claude/**",
    ".junie/**"
  ]
};
