export default {
  ignores: [
    "dist/*",
    "package-lock.json",
    "**/tsconfig*.json",
    "src/**/*.js",
    // Generated by scripts/gas/bundle.mjs from dist/.
    "scripts/gas/Library.js",
    // Vendored agent skills, kept byte-for-byte as their source publishes them.
    ".agents/**",
    ".claude/**",
    ".junie/**"
  ]
};
